import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/About.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App...</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="test1 test2 tset 3" />
        <link rel="icon" href="/favicon.ico" />
        <meta httpEquiv="Content-Language" content="en"/>
      </Head>
      <h2 className={styles.test}>test</h2>
      <h2 className={styles.test1}>test</h2>
      <a href="contact" style={{fontSize:'5rem'}}>contact</a><br />
      <a href="about" style={{fontSize:'5rem'}}>about</a>

     
        
    </div>
  )
}
