import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/About.module.scss'
import Link from 'next/link';
import { useSelector } from 'react-redux';
import { useEffect } from 'react';

export default function Home() {
  const posts = useSelector((state) => state.test);
  console.log(posts);
  // useEffect(()=>{
  // },[posts])
  return (
    <div className={styles.container}>
      <Head>
        <title>My title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="test1 test2 tset 3" />
        <link rel="icon" href="/favicon.ico" />
        <meta httpEquiv="Content-Language" content="en"/>
      </Head>
      
      <h2>Home Page</h2>

      <Link href='/about'><a className={styles.link2}>about</a></Link><br/>
      <Link href='/contact'><a className={styles.link2}>contact</a></Link><br />
      <Link href='/posts'><a className={styles.link2}>posts</a></Link><br />
      <Link href='/users'><a className={styles.link2}>users</a></Link><br />
      <Link href='/cases'><a className={styles.link2}>cases</a></Link>

    </div>
  )
}
